# Generated by Django 5.2.7 on 2025-10-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_videojuegos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='videojuegos',
        ),
    ]
